In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

import numpy as np
import cv2

In [36]:
### 3.4 Fourier Transform

# fourier transform in numpy
box_3 = np.full((3, ), 1 /3, dtype=np.float16)
print("Box 3")
print(box_3)
print(np.fft.fft(box_3))

box_5 = np.full((5, ), 1 /5, dtype=np.float16)
print("Box 5")
print(box_5)
print(np.fft.fft(box_5))

linear = np.array([1, 2, 1], dtype=np.float16) / 4.
print("Linear")
print(linear)
print(np.fft.fft(linear))

binomial = np.array([1, 4, 6, 4, 1], dtype=np.float16) / 16
print("Binomial")
print(binomial)
print(np.fft.fft(binomial))

sobel = np.array([-1, 0, 1], dtype=np.float16) / 2
print("Sobel")
print(sobel)
print(np.fft.fft(sobel))

corner = np.array([-1, 2, -1], dtype=np.float16) / 2
print("Corner")
print(corner)
print(np.fft.fft(corner))

Box 3
[0.3333 0.3333 0.3333]
[0.99975586+0.j 0.        +0.j 0.        +0.j]
Box 5
[0.2 0.2 0.2 0.2 0.2]
[9.99755859e-01+0.j 0.00000000e+00+0.j 1.38777878e-17+0.j
 1.38777878e-17+0.j 0.00000000e+00+0.j]
Linear
[0.25 0.5  0.25]
[ 1.   +0.j         -0.125-0.21650635j -0.125+0.21650635j]
Binomial
[0.0625 0.25   0.375  0.25   0.0625]
[ 1.        +0.j         -0.34656781-0.25179625j  0.00281781+0.00867233j
  0.00281781-0.00867233j -0.34656781+0.25179625j]
Sobel
[-0.5  0.   0.5]
[ 0.  +0.j        -0.75+0.4330127j -0.75-0.4330127j]
Corner
[-0.5  1.  -0.5]
[ 0.  +0.j         -0.75-1.29903811j -0.75+1.29903811j]
